### ISSUE TITLE
Think an update broke this plugin

### ISSUE THREAD

**Issue by CervonMi** [KiameV/openrct2.mod.queuetv#1]
Used to work great. Now it will cause a "Can't put this here" message (not exact text), also causes any windows open at the time to close.

**Comment by KiameV** [comment]
Hmm, I haven't played for a while. Let me update Open RCT2 and check it out

**Comment by KiameV** [comment]
Hopefully this works: https://github.com/KiameV/openrct2.mod.queuetv/releases/tag/1.0.1

**Comment by CervonMi** [comment]
confirmed. Thanks!
